server:
  port: 8888



spring:
  datasource:
    default:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/sys_common?characterEncoding=utf-8&serverTimezone=GMT%2B8&useUnicode=true&autoReconnect=true
      username: "root"
      password: "root"
